#!/usr/bin/env bash
# Configure and show subdomain details

fetch_information () {
	input_line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $input_line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]; then
	fetch_information "$1" "www"
	fetch_information "$1" "lb-01"
	fetch_information "$1" "web-01"
	fetch_information "$1" "web-02"
elif [ "$#" == 2 ]; then
	fetch_information "$1" "$2"
else
	exit
fi
