#!/usr/bin/env bash
#Install nginx web server

apt-get update
apt-get -y --allow-downgrades install nginx

mkdir /etc/nginx/html && touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "server {
	listen	80;
	listen	[::]:80 default_server;
	root	/etc/nginx/html;
	add_header X-Served-by $HOSTNAME;
	index	index.html index.htm;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
    }" > /etc/nginx/sites-available/default

service nginx restart
