#!/usr/bin/env bash
#The script installs and configures HAproxy on server `lb-01` server

apt-get update

apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.old} ; touch /etc/haproxy/haproxy.cfg

echo "	global
		log 127.0.0.1	local0
	       	log 127.0.0.1	local1 notice
		maxconn 	2000
		user		haproxy	
		group		haproxy
		daemon


	defaults	
		log	global
		mode	http
		option	httplog
		option	dontlognull
		retries 3
		option 	redispatch
		timeout	connect 5000
		timeout client 10000
		timeout server 10000


	listen hbnb	
		bind	*:80
		mode	http
		stats	enable
		stats	uri /haproxy?stats
		balance	roundrobin
		option 	httpclose
		option	forwardfor
		server	962-web-01 3.227.211.247:80 check
		server	962-web-02 3.236.123.188:80 check

" > /etc/haproxy/haproxy.cfg

service haproxy start
