#!/usr/bin/env bash
# Nginx server configuration script to listen on port 80
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

if pgrep "nginx"
then
	sudo service nginx restart
else
	sudo service nginx start
fi
