#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely,
#+ with a `sleep 2` in between each interation, then
#+ "I am invincible!!!" when receiving a `SIGTERM` signal

i=0
while (( i>1 )); do
	echo "To infinity and beyond"
	sleep 2
	trap echo "I am invincible!!!"
done
